# Read the documentation at https://github.com/thephpleague/flysystem-bundle/blob/master/docs/1-getting-started.md
services:
  minio_client:
    class: 'Aws\S3\S3Client'
    arguments:
      -   endpoint: '%env(AWS_ENDPOINT)%'
          region: '%env(AWS_DEFAULT_REGION)%'
          use_path_style_endpoint: true
          credentials:
            key: '%env(AWS_ACCESS_KEY_ID)%'
            secret: '%env(AWS_SECRET_ACCESS_KEY)%'

flysystem:
  storages:
    default.storage:
      adapter: 'local'
      options:
        directory: '%kernel.project_dir%/var/storage/default'
    minio.storage:
      adapter: 'aws'
      options:
        client: 'minio_client' # The service ID of the Aws\S3\S3Client instance
        bucket: '%env(AWS_BUCKET)%'
        streamReads: true
