image: php:8.3-cli

stages:
  - build
  - test
  - deploy

cache:
  key: ${CI_COMMIT_REF_SLUG}
  paths:
    - vendor/

variables:
  POSTGRES_HOST_AUTH_METHOD: trust
  APP_ENV: "test"
  DATABASE_URL: "postgresql://${POSTGRES_USER}:${POSTGRES_PASSWORD}@postgres:5432/${POSTGRES_DB}"

  before_script:
    - echo "Генерация ACCESS_SECRET (42 символа)"
    - export ACCESS_SECRET=$(openssl rand -hex 21)
    - echo "ACCESS_SECRET=$ACCESS_SECRET" >> .env
    - echo "Записываем DATABASE_URL и APP_ENV в .env"
    - echo "DATABASE_URL=$DATABASE_URL" >> .env
    - echo "APP_ENV=$APP_ENV" >> .env
    - if [ "$APP_ENV" = "test" ]; then echo "Добавляем ID_PROSV_CLIENT_ID в .env.test"; echo "ID_PROSV_CLIENT_ID=$ID_PROSV_CLIENT_ID" >> .env.test; fi
    - if [ "$APP_ENV" = "test" ]; then echo "Добавляем ID_PROSV_CLIENT_SECRET в .env.test"; echo "ID_PROSV_CLIENT_SECRET=$ID_PROSV_CLIENT_SECRET" >> .env.test; fi

build:
  stage: build
  script:
    - echo "Обновление списка пакетов и установка зависимостей"
    - apt-get update && apt-get install -y unzip libz-dev libssl-dev
    - echo "Установка Composer"
    - curl -sS https://getcomposer.org/installer | php -- --install-dir=/usr/local/bin --filename=composer
    - echo "Установка зависимостей Composer"
    - composer install --prefer-dist --no-progress --no-suggest
  artifacts:
    paths:
      - vendor/
      - .env

test:
  stage: test
  services:
    - postgres:13
  script:
    - echo "Проверка версии PHP"
    - php -v
    - echo "Установка Redis через pecl и включение расширения"
    - php -m | grep -q redis || (pecl install redis && docker-php-ext-enable redis)
    - echo "Устанавливаем libpq-dev для сборки pdo_pgsql"
    - apt-get update && apt-get install -y libpq-dev postgresql-client
    - echo "Устанавливаем PHP-расширения pdo_pgsql и pgsql"
    - docker-php-ext-install pdo_pgsql pgsql
    - echo "Проверка версии psql"
    - psql --version
    - echo "Выполняем миграции Doctrine"
    - php bin/console doctrine:migrations:migrate --no-interaction
    - echo "Наполнение базы данных командой app:update-props"
    - php bin/console app:update-props
    - echo "Наполнение базы данных тестовыми данными командой app:test-data"
    - php bin/console app:test-data
    - echo "Запуск тестов с выводом покрытия"
    - php bin/phpunit --coverage-text --colors=never
  allow_failure: false

deploy:
  stage: deploy
  script:
    - echo "Установка SSH клиента и rsync для деплоя"
    - apt-get update && apt-get install -y openssh-client rsync
    - echo "Настройка SSH-ключей"
    - mkdir -p ~/.ssh
    - echo "$SSH_PRIVATE_KEY" | tr -d '\r' > ~/.ssh/id_rsa
    - chmod 600 ~/.ssh/id_rsa
    - ssh-keyscan $DEPLOY_SERVER >> ~/.ssh/known_hosts
    - echo "Выполняем rsync для деплоя на сервер"
    - rsync -q -avz --delete ./ deployer@$DEPLOY_SERVER:/var/www/app
    - ssh deployer@$DEPLOY_SERVER "cd /var/www/app && php bin/console cache:clear --env=$APP_ENV"
    - ssh deployer@$DEPLOY_SERVER "cd /var/www/app && php bin/console cache:warmup --env=$APP_ENV"
    - ssh deployer@$DEPLOY_SERVER "cd /var/www/app && php bin/console doctrine:migrations:migrate --no-interaction --env=$APP_ENV"
  only:
    - main
